### ISSUE TITLE
Don't work mobile menu on iphone

### ISSUE THREAD

**Issue by vasilukwolf** [CherryFramework/CherryFramework#24]
Do nor print select for ios and chrome http://www.nidarosda.no/

**Comment by cheh** [comment]
Hi, @vasilukwolf. Topical? 
Because on my
iphone 5s + ios 8.1.4 + chrome 
looks good - 
![img_3291](https://cloud.githubusercontent.com/assets/2461627/10077227/2584926e-62e8-11e5-80c5-15f73813f178.PNG)

**Comment by vasilukwolf** [comment]
Now not actual. Project close. Thanks!
