### ISSUE TITLE
Strict Standards: Only variables should be passed by reference in /path/wp-content/themes/CherryFramework/functions.php on line 279

### ISSUE THREAD

**Issue by loorlab** [CherryFramework/CherryFramework#27]
Hi CF, the framework is generating the following notice with theme http://www.templatemonster.com/wordpress-themes/47536.html :

Strict Standards: Only variables should be passed by reference in /path/wp-content/themes/CherryFramework/functions.php on line 279

Strict Standards: Only variables should be assigned by reference in /path/wp-content/themes/CherryFramework/functions.php on line 279

Strict Standards: Only variables should be passed by reference in /path/wp-content/themes/CherryFramework/functions.php on line 279

Strict Standards: Only variables should be assigned by reference in /path/wp-content/themes/CherryFramework/functions.php on line 279

why this occurs?

Thanks Friends !

**Comment by cheh** [comment]
CherryFramework version?

**Comment by loorlab** [comment]
Sorry, our information:

Cherry Framework
Name:cherry
Author:Template_Help.com
Your Version:2.3.1
Update Version:2.4
Backup Version:No backup.
Last Backup Date:No backup.
Description:A theme for Wordpress 3.6.x

**Comment by cheh** [comment]
Hi, @loorlab!

In version 3.1.5 this `strict standards` resolved.
