### ISSUE TITLE
The called constructor method for WP_Widget is deprecated since version 4.3.0!

### ISSUE THREAD

**Issue by loorlab** [CherryFramework/CherryFramework#30]
Hi CF, again Notices with our Templates on CherryFramework 

instead. in /path/wp-includes/functions.php on line 3457

Notice: The called constructor method for WP_Widget is deprecated since version 4.3.0! Use

**Comment by cheh** [comment]
Hi, @loorlab!

We released bug-fixed version for `cherry-plugin`. Please, upgrader.

P.S. If problem not resolved - send your question to support.
