### ISSUE TITLE
CherryFramework 4.0.5.1 Install error

### ISSUE THREAD

**Issue by chidinweke** [CherryFramework/CherryFramework#39]
Hello

I downloaded the CherryFramework 4.0.5.1 and i'm getting this error.

Fatal error: Call to undefined function wp_styles() in C:\wamp\www\frameworkbootframe\wp-content\themes\cherry\lib\classes\class-cherry-api-js.php on line 71

Screeenshot https://gyazo.com/23c40f03f2ea1d68473e652210496ee3

**Comment by cheh** [comment]
Hello, @chidinweke.

Please, update WP engine in your site to the latest version, because function `wp_styles ` since 4.2.0.
