### ISSUE TITLE
Fatal Error when running PHP 7.1

### ISSUE THREAD

**Issue by brandonpeat** [CherryFramework/CherryFramework#53]
Switched my server to PHP 7.1 and the site crashed, here's the error I got:

Fatal Error (E_COMPILE_ERROR): 'continue' not in the 'loop' or 'switch' context occurred in wp-content/plugins/cherry-plugin/includes/widgets/widgets-manager.php on line 563.

Switched back to PHP 5.6 and it worked again. Is there a fix yet for 7.1? I need to get that server upgraded.

**Comment by brandonpeat** [comment]
Looks like somebody else had this same problem in #36 , it was closed but I don't see a solution??

**Comment by brandonpeat** [comment]
Looks like the site in question is running Cherry 3.1.5, which I'm guessing is end-of-lifed with no PHP 7.1 support planned? I inherited this site from a prior developer so I've finding lots of these fun surprises. Thanks.

**Comment by DuckDivers** [comment]
Change line 564 of /plugins/cherry-plugin/includes/widgets/widgets-manager.php from:

`	if ( !isset($wp_registered_widgets[$id]) ) continue;`
to
`	if ( !isset($wp_registered_widgets[$id]) ) return false;`

**Comment by brandonpeat** [comment]
That fixed it. Thanks!

**Comment by loretoparisi** [comment]
@brandonpeat @DuckDivers thanks guys I had exactly the same issue when trying `wp plugin list`. Question: will be this merged into the master at some point?

**Comment by christinairwin** [comment]
Thanks so much for posting this. I have seen this issue pop up on a client's WP theme a couple of times and I was searching for a way to fix it. That did the trick! Thanks again!

**Comment by loretoparisi** [comment]
@christinairwin it works, the only problem is that I'm not sure it has been released, and several templates did not get the update, so it is better to fix "by the hands"!

**Comment by Leonel4826** [comment]
Muchas Gracias, esto me ha funcionado! ---> return false;

**Comment by suppli3r** [comment]
The solutions was great.

It worked perfectly.

thanks a lot

**Comment by MisterWP** [comment]
> Change line 564 of /plugins/cherry-plugin/includes/widgets/widgets-manager.php from:
> 
> `	if ( !isset($wp_registered_widgets[$id]) ) continue;`
> to
> `	if ( !isset($wp_registered_widgets[$id]) ) return false;`

My hero

**Comment by kaydeeweb** [comment]
> Change line 564 of /plugins/cherry-plugin/includes/widgets/widgets-manager.php from:
> 
> `	if ( !isset($wp_registered_widgets[$id]) ) continue;`
> to
> `	if ( !isset($wp_registered_widgets[$id]) ) return false;`

Thanks so much DUCK DIVERS, this fixed my Heroic Gallery Manager plugin. 

For anyone else - I changed line 1043 on file ht-gallery-manager.php (in plugin root directory)

From: 

				continue;

To:
				return false;

**Comment by gxsoft** [comment]
Thank you@brandonpeat @DuckDivers #Great

**Comment by sarah4321** [comment]
I created an account here just so that I could say thank you to @DuckDivers for posting this solution. My problem was with a theme, but it worked like a charm. Thank you!!!

**Comment by Nikoyo** [comment]
I am very glad that I've found this easy solution ! Regards MisterWP

**Comment by neoarksoftware** [comment]
Wow..! It's working for me. I love this solution. 

Thanks Duck Divers,

**Comment by TCS-VM** [comment]
Followed instructions and changed  /plugins/cherry-plugin/includes/widgets/widgets-manager.php from:

if ( !isset($wp_registered_widgets[$id]) ) continue;
to
if ( !isset($wp_registered_widgets[$id]) ) return false;

That simple change got site up and running again, thanks DuckDivers.

**Comment by jolosimeon** [comment]
Just wanted to comment thanks to DuckDivers! Worked great.

**Comment by lobebe** [comment]
You are an angel....thank you for this.

**Comment by mariopaolucci** [comment]
HUGE thanks!
